Support for 3de v8 and compatibility changes with ayon-core
ynput/ayon-equalizer pull request #5
Opened 2024-09-27 07:53 UTC by antirotor

## Changelog Description
This PR is adding support for 3DEqualizer v8. It is also including fixes making this addon compatible with development in ayon core.

## Additional info
3DEqualizer v8 is using newer version of Python - 3.9, there are also changes in export scripts and the way they need to be executed. This PR is also fixing and adding some needed or broken pieces, like fixing addon version, fixing pre-launch hook for PySide2 installation, etc. 

## Testing notes:

1. Run 3Dequalizer v7 and v8
2. Try to load in a plate, track something
3. Publish out Matchmove scipts for Maya and Nuke
4. Publish out Lens distortion for Nuke

Closes #4
Closes #3

2024-10-01 10:50 UTC, iLLiCiTiT commented on client/ayon_equalizer/__init__.py
> +"""Ayon Equalizer Addon."""
```suggestion
"""AYON Equalizer Addon."""
```

2024-10-01 10:51 UTC, iLLiCiTiT commented on client/ayon_equalizer/addon.py
> +    enabled = True
Enabled is by default set to `True`.

2024-10-01 10:51 UTC, iLLiCiTiT commented on client/ayon_equalizer/addon.py
> +    def get_launch_hook_paths(self):
Why was removed host validation?

2024-10-01 10:52 UTC, iLLiCiTiT commented on client/ayon_equalizer/api/host.py
> +    def ls(self):
Just a note: `ls` is not required method, `get_containers` is.

2024-10-01 10:53 UTC, iLLiCiTiT commented on client/ayon_equalizer/api/lib.py
> +"""Library functions for the Ayon Equalizer API."""
```suggestion
"""Library functions for the AYON Equalizer API."""
```

2024-10-01 10:54 UTC, iLLiCiTiT commented on client/ayon_equalizer/api/plugin.py
> +@six.add_metaclass(ABCMeta)
You don't need to add ABCMeta as `Creator` already has it as meta. Also don't use `six` please.

2024-10-01 10:56 UTC, iLLiCiTiT commented on client/ayon_equalizer/hooks/pre_pyside2_install.py
> +        except ImportError:
This might not raise just `ImportError` if it cannot be imported...

2024-10-01 10:57 UTC, iLLiCiTiT commented on client/ayon_equalizer/plugins/__init__.py
Plugins dir should not have `__init__.py`. It looks like it is a module that can be used for imports.

2024-10-01 10:58 UTC, iLLiCiTiT commented on client/ayon_equalizer/plugins/create/create_lens_distortion_data.py
> +            instance_data: dict, pre_create_data: dict):
```suggestion
        self,
        product_name: str,
        instance_data: dict,
        pre_create_data: dict
    ):
```

2024-10-01 10:59 UTC, iLLiCiTiT commented on client/ayon_equalizer/plugins/load/load_plate.py
> +        file_path = get_representation_path(repre_entity)
You can use implemented method on `LoaderPlugin`.
```suggestion
        file_path = self.filepath_from_context(repre_entity)
```

2024-10-01 11:02 UTC, iLLiCiTiT commented on client/ayon_equalizer/plugins/publish/extract_matchmove_script_maya.py
> +                    1 if attr_data["export_uv_textures"] else 0,
All these "1 or 0" can be simplified converting to bool and int:
```suggestion
                    int(bool(attr_data["export_uv_textures"])),
```

2024-10-01 12:09 UTC, MustafaJafar requested changes
The `client\ayon_equalizer\version.py` doesn't exist. 
and, `create_package.py` expects that file to modify, it doesn't create it if missing. 

Could you add it.

2024-10-01 12:36 UTC, iLLiCiTiT commented on create_package.py
This looks like outdated create package, could you try https://github.com/ynput/ayon-addon-template/blob/develop/create_package.py

2024-10-01 13:10 UTC, antirotor commented on client/ayon_equalizer/plugins/__init__.py
but it is used by Sphinx for auto-doc

2024-10-01 13:18 UTC, iLLiCiTiT commented on client/ayon_equalizer/hooks/pre_pyside2_install.py
> +            return process.returncode == 0
Why was moved from the try block?

2024-10-01 13:18 UTC, iLLiCiTiT commented on client/ayon_equalizer/plugins/__init__.py
> +"""Plugins for Ayon Equalizer."""
```suggestion
"""Plugins for AYON Equalizer."""
```

2024-10-01 13:18 UTC, iLLiCiTiT commented on client/ayon_equalizer/plugins/create/__init__.py
> +"""Creator plugin for Ayon Equalizer."""
```suggestion
"""Creator plugin for AYON Equalizer."""
```

2024-10-01 13:20 UTC, iLLiCiTiT commented on package.py
> +    "core": ">=0.3.0",
```suggestion
ayon_required_addons = {
    "core": ">=0.3.0",
```

2024-10-01 13:21 UTC, iLLiCiTiT commented on tools/manage.ps1
> +$env:PSModulePath = $env:PSModulePath + ";$($ayon_root)\tools\modules\powershell"
```suggestion
$env:PSModulePath = $env:PSModulePath + ";$($RepoRoot)\tools\modules\powershell"
```

2024-10-01 13:41 UTC, MustafaJafar commented on create_package.py
I tested it and indeed the `create_package.py` is old but it also expects the `version.py` file to exist.

2024-10-01 13:45 UTC, MustafaJafar commented on tools/manage.ps1
> +$env:PSModulePath = $env:PSModulePath + ";$($ayon_root)\tools\modules\powershell"
I've just found this also needs to change in core addon

2024-10-01 14:15 UTC, antirotor commented on client/ayon_equalizer/addon.py
> +    def get_launch_hook_paths(self):
I must admit I don't understand that check? Why is it even needed? Why on this specific method?

2024-10-01 15:02 UTC, MustafaJafar commented on client/ayon_equalizer/api/plugin.py
>          self.host.update_context_data(context, changes=update_list)
I got an error here.
![image](https://github.com/user-attachments/assets/8e696b07-7504-4f3a-952c-850ad33b0727)

2024-10-01 22:33 UTC, antirotor commented on package.py
> +    "core": ">=0.3.0",
what's the difference?

2024-10-01 22:38 UTC, antirotor commented on client/ayon_equalizer/api/plugin.py
>          self.host.update_context_data(context, changes=update_list)
should be fine now

2024-10-01 22:40 UTC, antirotor commented on client/ayon_equalizer/hooks/pre_pyside2_install.py
> +            return process.returncode == 0
because of https://docs.astral.sh/ruff/rules/try-consider-else/

2024-10-01 22:41 UTC, antirotor commented on client/ayon_equalizer/plugins/publish/extract_matchmove_script_maya.py
> +                    1 if attr_data["export_uv_textures"] else 0,
maybe little simplified but at least for me it is more readable and explicit that it really requires `1` an `0` and not bool

2024-10-01 22:45 UTC, antirotor commented on client/ayon_equalizer/plugins/create/create_lens_distortion_data.py
> +            instance_data: dict, pre_create_data: dict):
right you are, no need for that. There was some code there at one point.

2024-10-02 15:05 UTC, iLLiCiTiT commented on package.py
> +    "core": ">=0.3.0",
I don't know, you have "some" newline character there?

![image](https://github.com/user-attachments/assets/988a0355-89d2-4c27-a49d-84b47f4f7a22)

2024-10-02 15:09 UTC, iLLiCiTiT commented on client/ayon_equalizer/addon.py
> +    def add_implementation_envs(self, env: dict, _app: str) -> None:
It is `Application` from `ayon_applications.defs`, not `str`.
```suggestion
    def add_implementation_envs(self, env: dict, _app: Any) -> None:
```

2024-10-02 15:11 UTC, iLLiCiTiT commented on client/ayon_equalizer/addon.py
> +    def get_launch_hook_paths(self):
Hmm, maybe you're right.

2024-10-02 15:17 UTC, iLLiCiTiT commented on create_package.py
> +    r"""Allows longer paths in zip files.
Why? Because there is `\\?\` in the docstring? OMG...

2024-10-02 16:14 UTC, MustafaJafar reviewed
I wonder why when loading something, 
- I can't find it in the scene inventory/manage. 
- Also, why, does it disappear from the loader. 
![image](https://github.com/user-attachments/assets/46cfbcc6-1f32-433d-9d40-467f399666e5)

2024-10-11 08:51 UTC, antirotor commented
Tested in v7 and v8, publishing, loading and managing works. v7 is little bit less stable.

2024-10-11 09:25 UTC, iLLiCiTiT commented on client/ayon_equalizer/api/host.py
> +
```suggestion
```

2024-10-11 09:25 UTC, iLLiCiTiT commented on client/ayon_equalizer/api/host.py
> +
There are 3 empty lines here?

2024-10-11 09:27 UTC, iLLiCiTiT commented on client/ayon_equalizer/api/host.py
> +            ayon_data[EQUALIZER_CONTEXT_KEY] = []
You don't need to do that...
```suggestion
```

2024-10-11 09:28 UTC, iLLiCiTiT commented on client/ayon_equalizer/api/host.py
> +            instance: CreatedInstance,
Why passing whole instance? Could be just `instance_id`.

2024-10-11 09:29 UTC, iLLiCiTiT commented on client/ayon_equalizer/api/host.py
> +    def remove_publish_instance(self, instance: CreatedInstance) -> None:
And again, instance is used only to get it's id, you can expect only id.
```suggestion
    def remove_create_instance(self, instance: CreatedInstance) -> None:
```

2024-10-14 11:48 UTC, antirotor commented
@MustafaJafar could you please eventually retest? Should be ok now (famous last words).

2024-10-14 14:23 UTC, MustafaJafar approved these changes
> @MustafaJafar could you please eventually retest? Should be ok now (famous last words). BTW loading in Maya need some fixes for handling paths. But that needs PR in ayon-maya.

I gave it one more test. it looks smooth. AYON Tools works perfectly.
The steps I followed: 
- Publish `stA` official example footage using tray publisher.
- Load it as a plate in my 3de workfile.
- Use creator to create a matchmove instance
- Click Auto track button
- Triggered publishing

Here are my published data
[v001.zip](https://github.com/user-attachments/files/17365204/v001.zip)

2024-10-14 20:50 UTC, merged

2024-10-23 12:54 UTC, johhnry commented
> @MustafaJafar could you please eventually retest? Should be ok now (famous last words). BTW loading in Maya need some fixes for handling paths. But that needs PR in ayon-maya.

Subitted PR here: https://github.com/ynput/ayon-maya/pull/159